version: '3.1'
services:
  clay-tablet-db:
    container_name: 'clay-tablet-db'
    image: postgres:14
    restart: always
    ports:
      - 5499:5432
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'clay_tablet'
      POSTGRES_USER: 'postgres'
